version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    command: [ "redis-server", "--requirepass", "root" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "root", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: minhhau203/my-backend:latest
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  postgres-data:


      #version: '3.8'
      #services:
      #  backend:
      #    image: minhhau203/my-backend:latest  # Dùng image đã đẩy lên Docker Hub
      #    ports:
      #      - '8000:8000'
      #    environment:
      #      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-ctv2e08gph6c73eqj28g-a.oregon-postgres.render.com:5432/test_database_mt2x
      #      - SPRING_DATASOURCE_USERNAME=root
      #      - SPRING_DATASOURCE_PASSWORD=eJVlbnAkqC1x7F0X3qlKTylAkYULyq1x
      #    depends_on: []