server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: root
#    render db cloud
    url: jdbc:postgresql://dpg-cvvkuvruibrs73bhv2s0-a.oregon-postgres.render.com:5432/db_intern
    username: db_intern_user
    password: IcuPCl3dIAEs6Z0neoN2eNsuQoIrUu60
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhhau2803@gmail.com
    password: "btqu dogu ezmf qqdo"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#
#redis:
#  host: 127.0.0.1
#  port: 6379
#  password: root
#  ssl: false

redis:
  host: quiet-ant-13751.upstash.io
  port: 6379
  password: ATW3AAIjcDE2OTc5MWI4MzNhNjU0YjNhYWFmYjc5MzRkMzFjYTZkZXAxMA
  ssl: true
file:
  upload-dir: uploads/

jwt:
  signerKey: "KUJOzbCuK/OeoCghRlx37paZxItqk17Fg62DMJNdH5gIeEsz1sN2b15SvP8aY7fV"
