server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  mail:
    host: smtp.gmail.com
    port: 587
    username: minhhau2803@gmail.com
    password: "btqu dogu ezmf qqdo"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

redis:
  host: 127.0.0.1
  port: 6379
  password: root
  ssl: false

file:
  upload-dir: uploads/

jwt:
  signerKey: "KUJOzbCuK/OeoCghRlx37paZxItqk17Fg62DMJNdH5gIeEsz1sN2b15SvP8aY7fV"
